// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarranTeaApi.Data;

#nullable disable

namespace WarranTeaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313020454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e5555555-5555-5555-5555-555555555555",
                            ConcurrencyStamp = "e5555555-5555-5555-5555-555555555555",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d4444444-4444-4444-4444-444444444444",
                            RoleId = "e5555555-5555-5555-5555-555555555555"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WarranTeaApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "Laptops",
                            Description = "Apple's flagship professional laptop.",
                            Name = "MacBook Pro 16\""
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            Category = "Smartphones",
                            Description = "Samsung's premium flagship smartphone.",
                            Name = "Galaxy S25 Ultra"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dyson",
                            Category = "Home Appliances",
                            Description = "Cordless vacuum with laser dust detection.",
                            Name = "Dyson V15 Detect"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Sony",
                            Category = "Audio",
                            Description = "Industry-leading noise cancelling headphones.",
                            Name = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "LG",
                            Category = "TVs",
                            Description = "65-inch OLED 4K smart TV.",
                            Name = "LG C4 65\" OLED TV"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "KitchenAid",
                            Category = "Kitchen Appliances",
                            Description = "Iconic tilt-head stand mixer.",
                            Name = "KitchenAid Artisan Stand Mixer"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Dell",
                            Category = "Laptops",
                            Description = "Premium 15-inch ultrabook.",
                            Name = "Dell XPS 15"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Bose",
                            Category = "Audio",
                            Description = "Premium noise cancelling headphones with spatial audio.",
                            Name = "Bose QuietComfort Ultra"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Apple",
                            Category = "Tablets",
                            Description = "Apple's most advanced tablet with M4 chip.",
                            Name = "iPad Pro 13\""
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Sony",
                            Category = "Gaming",
                            Description = "Next-gen gaming console with enhanced GPU.",
                            Name = "PlayStation 5 Pro"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "iRobot",
                            Category = "Home Appliances",
                            Description = "Self-emptying robot vacuum with obstacle avoidance.",
                            Name = "Roomba j9+"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Canon",
                            Category = "Cameras",
                            Description = "Full-frame mirrorless camera with 24.2 MP sensor.",
                            Name = "Canon EOS R6 Mark II"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Samsung",
                            Category = "Storage",
                            Description = "PCIe 4.0 NVMe M.2 solid state drive.",
                            Name = "Samsung 990 Pro 2TB SSD"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Breville",
                            Category = "Kitchen Appliances",
                            Description = "Semi-automatic espresso machine with built-in grinder.",
                            Name = "Breville Barista Express"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "LG",
                            Category = "Home Appliances",
                            Description = "Single-unit washer and dryer tower with AI technology.",
                            Name = "LG WashTower"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Nintendo",
                            Category = "Gaming",
                            Description = "Hybrid home and portable gaming console.",
                            Name = "Nintendo Switch 2"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Sonos",
                            Category = "Audio",
                            Description = "Premium Dolby Atmos soundbar for home theater.",
                            Name = "Sonos Arc Soundbar"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "HP",
                            Category = "Laptops",
                            Description = "Premium 2-in-1 convertible laptop.",
                            Name = "HP Spectre x360 16\""
                        },
                        new
                        {
                            Id = 19,
                            Brand = "GoPro",
                            Category = "Cameras",
                            Description = "Waterproof action camera with HyperSmooth stabilization.",
                            Name = "GoPro Hero 12 Black"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Whirlpool",
                            Category = "Kitchen Appliances",
                            Description = "36-inch counter-depth French door refrigerator.",
                            Name = "Whirlpool French Door Refrigerator"
                        });
                });

            modelBuilder.Entity("WarranTeaApi.Models.ProductWarranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductWarranties");
                });

            modelBuilder.Entity("WarranTeaApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1111111-1111-1111-1111-111111111111",
                            Email = "alice@warrantea.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Alice Johnson",
                            NormalizedEmail = "ALICE@WARRANTEA.COM",
                            NormalizedUserName = "ALICE@WARRANTEA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMgiG61xRN17mHZ+k+BC3HvTdCOoDUVQ9g5vhfRPuEFALWkOJ8210fvk1p0ZGTkiEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ALICE_STAMP",
                            TwoFactorEnabled = false,
                            UserName = "alice@warrantea.com"
                        },
                        new
                        {
                            Id = "b2222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2222222-2222-2222-2222-222222222222",
                            Email = "bob@warrantea.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bob Smith",
                            NormalizedEmail = "BOB@WARRANTEA.COM",
                            NormalizedUserName = "BOB@WARRANTEA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKJuR6jqLqYCbb+eg7NWNtXTRqCDk+DYas3WVRs7RE7XJLay1lwN1zFkNANUZBuU6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "BOB_STAMP",
                            TwoFactorEnabled = false,
                            UserName = "bob@warrantea.com"
                        },
                        new
                        {
                            Id = "c3333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c3333333-3333-3333-3333-333333333333",
                            Email = "carol@warrantea.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Carol Davis",
                            NormalizedEmail = "CAROL@WARRANTEA.COM",
                            NormalizedUserName = "CAROL@WARRANTEA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKpglDewuRVeSCltWMWRaxhXPyVh0D1QMzFwxiPP4NGd+XCJq4CkiW9ry9A1wsypew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CAROL_STAMP",
                            TwoFactorEnabled = false,
                            UserName = "carol@warrantea.com"
                        },
                        new
                        {
                            Id = "d4444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4444444-4444-4444-4444-444444444444",
                            Email = "admin@warrantea.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin User",
                            NormalizedEmail = "ADMIN@WARRANTEA.COM",
                            NormalizedUserName = "ADMIN@WARRANTEA.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEzd1J0oDvs10mJQ10SQ58vj3EUUu/1onvgrhlWffWKg+E74tuNXC30tmizKDgVxHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ADMIN_STAMP",
                            TwoFactorEnabled = false,
                            UserName = "admin@warrantea.com"
                        });
                });

            modelBuilder.Entity("WarranTeaApi.Models.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarrantyDocUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Warranties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Category = "Laptops",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "AppleCare+ purchased at time of sale.",
                            ProductId = 1,
                            ProductName = "MacBook Pro 16\"",
                            PurchaseDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            Category = "Smartphones",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Carrier-purchased device.",
                            ProductId = 2,
                            ProductName = "Galaxy S25 Ultra",
                            PurchaseDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Dyson",
                            Category = "Home Appliances",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Registered on Dyson website.",
                            ProductId = 3,
                            ProductName = "Dyson V15 Detect",
                            PurchaseDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Sony",
                            Category = "Audio",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2026, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Best Buy Geek Squad protection.",
                            ProductId = 4,
                            ProductName = "Sony WH-1000XM5",
                            PurchaseDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "LG",
                            Category = "TVs",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Post-holiday purchase. Wall mounted.",
                            ProductId = 5,
                            ProductName = "LG C4 65\" OLED TV",
                            PurchaseDate = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            Category = "Tablets",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Uses Magic Keyboard accessory.",
                            ProductId = 9,
                            ProductName = "iPad Pro 13\"",
                            PurchaseDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Sony",
                            Category = "Gaming",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Gift from spouse.",
                            ProductId = 10,
                            ProductName = "PlayStation 5 Pro",
                            PurchaseDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expiring-soon",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Canon",
                            Category = "Cameras",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Canon CarePAK PLUS registered.",
                            ProductId = 12,
                            ProductName = "Canon EOS R6 Mark II",
                            PurchaseDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Breville",
                            Category = "Kitchen Appliances",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Daily use espresso machine.",
                            ProductId = 14,
                            ProductName = "Breville Barista Express",
                            PurchaseDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expired",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Sonos",
                            Category = "Audio",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Living room setup.",
                            ProductId = 17,
                            ProductName = "Sonos Arc Soundbar",
                            PurchaseDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expired",
                            UserId = "a1111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Apple",
                            Category = "Laptops",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Work laptop. Standard 1-year only.",
                            ProductId = 1,
                            ProductName = "MacBook Pro 16\"",
                            PurchaseDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Dyson",
                            Category = "Home Appliances",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Extended guarantee via Dyson website.",
                            ProductId = 3,
                            ProductName = "Dyson V15 Detect",
                            PurchaseDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "KitchenAid",
                            Category = "Kitchen Appliances",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2027, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Wedding gift — 5-year manufacturer warranty.",
                            ProductId = 6,
                            ProductName = "KitchenAid Artisan Stand Mixer",
                            PurchaseDate = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            Category = "Laptops",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Premium Support Plus active.",
                            ProductId = 7,
                            ProductName = "Dell XPS 15",
                            PurchaseDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Bose",
                            Category = "Audio",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Bought refurbished from Bose outlet.",
                            ProductId = 8,
                            ProductName = "Bose QuietComfort Ultra",
                            PurchaseDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expired",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "iRobot",
                            Category = "Home Appliances",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "iRobot Complete Care plan.",
                            ProductId = 11,
                            ProductName = "Roomba j9+",
                            PurchaseDate = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Samsung",
                            Category = "Storage",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2029, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Installed in desktop PC. 5-year warranty.",
                            ProductId = 13,
                            ProductName = "Samsung 990 Pro 2TB SSD",
                            PurchaseDate = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "LG",
                            Category = "Home Appliances",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Premium Care plan purchased from Home Depot.",
                            ProductId = 15,
                            ProductName = "LG WashTower",
                            PurchaseDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Nintendo",
                            Category = "Gaming",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Launch day purchase.",
                            ProductId = 16,
                            ProductName = "Nintendo Switch 2",
                            PurchaseDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Whirlpool",
                            Category = "Kitchen Appliances",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Extended service plan. Ice maker replaced once.",
                            ProductId = 20,
                            ProductName = "Whirlpool French Door Refrigerator",
                            PurchaseDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "b2222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "Samsung",
                            Category = "Smartphones",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Samsung Care+ with theft protection.",
                            ProductId = 2,
                            ProductName = "Galaxy S25 Ultra",
                            PurchaseDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Sony",
                            Category = "Audio",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Amazon purchase. Standard warranty.",
                            ProductId = 4,
                            ProductName = "Sony WH-1000XM5",
                            PurchaseDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expired",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 23,
                            Brand = "LG",
                            Category = "TVs",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "4th of July sale. Standard warranty only.",
                            ProductId = 5,
                            ProductName = "LG C4 65\" OLED TV",
                            PurchaseDate = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Bose",
                            Category = "Audio",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Extended from Bose direct.",
                            ProductId = 8,
                            ProductName = "Bose QuietComfort Ultra",
                            PurchaseDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Apple",
                            Category = "Tablets",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Student discount purchase.",
                            ProductId = 9,
                            ProductName = "iPad Pro 13\"",
                            PurchaseDate = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 26,
                            Brand = "Sony",
                            Category = "Gaming",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "GameStop protection plan.",
                            ProductId = 10,
                            ProductName = "PlayStation 5 Pro",
                            PurchaseDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Breville",
                            Category = "Kitchen Appliances",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2028, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Extended coverage from Williams Sonoma.",
                            ProductId = 14,
                            ProductName = "Breville Barista Express",
                            PurchaseDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 28,
                            Brand = "HP",
                            Category = "Laptops",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2027, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "HP Care Pack 3-year on-site.",
                            ProductId = 18,
                            ProductName = "HP Spectre x360 16\"",
                            PurchaseDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 29,
                            Brand = "GoPro",
                            Category = "Cameras",
                            CoverageType = "Extended",
                            ExpirationDate = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "GoPro Subscription — annual renewal.",
                            ProductId = 19,
                            ProductName = "GoPro Hero 12 Black",
                            PurchaseDate = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "active",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 30,
                            Brand = "Whirlpool",
                            Category = "Kitchen Appliances",
                            CoverageType = "Manufacturer",
                            ExpirationDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Costco purchase. Considering extended plan.",
                            ProductId = 20,
                            ProductName = "Whirlpool French Door Refrigerator",
                            PurchaseDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "expired",
                            UserId = "c3333333-3333-3333-3333-333333333333"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WarranTeaApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WarranTeaApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarranTeaApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WarranTeaApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarranTeaApi.Models.ProductWarranty", b =>
                {
                    b.HasOne("WarranTeaApi.Models.Product", "Product")
                        .WithMany("ProductWarranties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarranTeaApi.Models.Warranty", b =>
                {
                    b.HasOne("WarranTeaApi.Models.Product", "Product")
                        .WithMany("Warranties")
                        .HasForeignKey("ProductId");

                    b.HasOne("WarranTeaApi.Models.User", "User")
                        .WithMany("Warranties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarranTeaApi.Models.Product", b =>
                {
                    b.Navigation("ProductWarranties");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("WarranTeaApi.Models.User", b =>
                {
                    b.Navigation("Warranties");
                });
#pragma warning restore 612, 618
        }
    }
}
