import type { User, Warranty, Product } from "~/types";

export const mockUser: User = {
  id: "1",
  name: "Alex Johnson",
  email: "alex.johnson@email.com",
  avatarUrl: undefined,
};

export const mockWarranties: Warranty[] = [
  {
    id: "1",
    productName: 'MacBook Pro 16"',
    brand: "Apple",
    category: "Electronics",
    purchaseDate: "2025-06-15",
    expirationDate: "2026-06-15",
    status: "active",
    coverageType: "Manufacturer",
    notes: "AppleCare+ included",
  },
  {
    id: "2",
    productName: 'Samsung 65" OLED TV',
    brand: "Samsung",
    category: "Electronics",
    purchaseDate: "2025-01-10",
    expirationDate: "2026-03-20",
    status: "expiring-soon",
    coverageType: "Extended",
    notes: "Best Buy extended warranty",
  },
  {
    id: "3",
    productName: "Dyson V15 Vacuum",
    brand: "Dyson",
    category: "Home Appliances",
    purchaseDate: "2024-08-20",
    expirationDate: "2026-08-20",
    status: "active",
    coverageType: "Manufacturer",
  },
  {
    id: "4",
    productName: "Sony WH-1000XM5 Headphones",
    brand: "Sony",
    category: "Electronics",
    purchaseDate: "2024-12-01",
    expirationDate: "2025-12-01",
    status: "expired",
    coverageType: "Manufacturer",
  },
  {
    id: "5",
    productName: "KitchenAid Stand Mixer",
    brand: "KitchenAid",
    category: "Home Appliances",
    purchaseDate: "2025-09-05",
    expirationDate: "2027-09-05",
    status: "active",
    coverageType: "Manufacturer",
    notes: "Hassle-free replacement warranty",
  },
  {
    id: "6",
    productName: "LG Front Load Washer",
    brand: "LG",
    category: "Home Appliances",
    purchaseDate: "2025-03-18",
    expirationDate: "2026-03-18",
    status: "expiring-soon",
    coverageType: "Extended",
  },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    name: 'MacBook Pro 16"',
    brand: "Apple",
    category: "Laptops",
    warrantyDuration: "1 Year",
    warrantyType: "Manufacturer Limited Warranty",
    description:
      "Covers manufacturing defects. AppleCare+ available for extended coverage.",
  },
  {
    id: "2",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    warrantyDuration: "1 Year",
    warrantyType: "Manufacturer Limited Warranty",
    description: "Standard Samsung warranty covers hardware defects.",
  },
  {
    id: "3",
    name: "Dyson V15 Detect",
    brand: "Dyson",
    category: "Home Appliances",
    warrantyDuration: "2 Years",
    warrantyType: "Manufacturer Warranty",
    description: "Parts and labor coverage for manufacturing defects.",
  },
  {
    id: "4",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Audio",
    warrantyDuration: "1 Year",
    warrantyType: "Manufacturer Limited Warranty",
    description: "Covers defects in materials and workmanship.",
  },
  {
    id: "5",
    name: 'LG C4 65" OLED TV',
    brand: "LG",
    category: "TVs",
    warrantyDuration: "1 Year",
    warrantyType: "Manufacturer Limited Warranty",
    description: "In-home service for eligible repairs during warranty period.",
  },
  {
    id: "6",
    name: "KitchenAid Artisan Stand Mixer",
    brand: "KitchenAid",
    category: "Kitchen Appliances",
    warrantyDuration: "5 Years",
    warrantyType: "Hassle-Free Replacement Warranty",
    description: "Full replacement warranty for manufacturing defects.",
  },
  {
    id: "7",
    name: "Dell XPS 15",
    brand: "Dell",
    category: "Laptops",
    warrantyDuration: "1 Year",
    warrantyType: "Premium Support",
    description: "24/7 tech support and next-business-day on-site service.",
  },
  {
    id: "8",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "Audio",
    warrantyDuration: "1 Year",
    warrantyType: "Manufacturer Limited Warranty",
    description: "Coverage against defects in materials and workmanship.",
  },
];
